version: "3"
volumes:
  postgres_data:

services:
  postgresql:
    image: postgres:16
    container_name: demo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      # 将postgres_data这个volume挂载到postgresql的默认数据存储路径
      # 因此DB的数据不会因为容器的挂掉而消失
      - postgres_data:/var/lib/postgresql/data