#!/bin/bash

echo "Running pre-commit hook to check commit message..."

gradle checkstyleMain --offline

# 如果上一个命令失败，则异常退出
if [ $? -ne 0 ]; then
    echo "Need to fix coding style issue before commit."
    exit 1
fi

echo "Pre-commit hook completed successfully"
exit 0