#!/bin/bash

echo "Running pre-push hook..."

./gradlew spotbugsMain

# 如果上一个命令失败，则异常退出
if [ $? -ne 0 ]; then
    echo "Need to fix coding smell issue before push."
    exit 1
fi

echo "Pre-push hook completed successfully"
exit 0