#!/bin/bash

echo "Running pre-push hook..."

./gradlew spotbugsMain
if [ $? -ne 0 ]; then
    echo "Need to fix coding smell issue before push."
    exit 1
fi

./gradlew ossIndexAudit
if [ $? -ne 0 ]; then
    echo "Need to fix dependency vulnerabilities before push."
    exit 1
fi

echo "Pre-push hook completed successfully"
exit 0